import { Expect } from "../away/Expect";
import { OnException } from "../away/OnException";
import { IsAlphabetic } from "../strings/Strings";

const EscapeCode = "00";

/** see: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 */
export function ExpectIso31661A2CountryCode(data:string,onBadData?:OnException){
    Expect(data.length===2,`Not an ISO3166-1 alpha-2 value. Expected length: 2.`,onBadData);
    Expect(IsAlphabetic(data)||EscapeCode,`Not an ISO3166-1 alpha-2 value. Expected alphabetic values or 00.`,onBadData);
}

export function ExpectAssignedIso31661A2CountryCode(data:string,onBadData?:OnException){
    ExpectIso31661A2CountryCode(data,onBadData);
    Expect(AssignedIso31661A2CountryCodes.includes(data as any),`Not a valid assigned Iso3166A2 country code.`);
}

/** Returns the name (hopefully). Will throw if you don't provide a valid country code. Will not throw if you simply provide an unassigned countrycode. */
export function MaybeGetIso31661A2CountryCodeEnglishName(countryCode:string):string|undefined{
    ExpectIso31661A2CountryCode(countryCode);
    return dataMap[countryCode.toUpperCase()]?.en;
}

/** Officially assigned codes. see: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 */
export type AssignedIso31661A2CountryCode = typeof AssignedIso31661A2CountryCodes[number];
/** Officially assigned codes. */
export const AssignedIso31661A2CountryCodes = [
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IS",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW",
] as const;

const dataMap:{
    [code:string]:{
        en:string,
        flagEmoji:string,
    }
} = {
    "AD": {en: "Andorra", flagEmoji:"🇦🇩"}, 
    "AE": {en: "United Arab Emirates", flagEmoji:"🇦🇪"}, 
    "AF": {en: "Afghanistan", flagEmoji:"🇦🇫"}, 
    "AG": {en: "Antigua and Barbuda", flagEmoji:"🇦🇬"}, 
    "AI": {en: "Anguilla", flagEmoji:"🇦🇮"}, 
    "AL": {en: "Albania", flagEmoji:"🇦🇱"}, 
    "AM": {en: "Armenia", flagEmoji:"🇦🇲"}, 
    "AO": {en: "Angola", flagEmoji:"🇦🇴"}, 
    "AQ": {en: "Antarctica", flagEmoji:"🇦🇶"}, 
    "AR": {en: "Argentina", flagEmoji:"🇦🇷"}, 
    "AS": {en: "American Samoa", flagEmoji:"🇦🇸"}, 
    "AT": {en: "Austria", flagEmoji:"🇦🇹"}, 
    "AU": {en: "Australia", flagEmoji:"🇦🇺"}, 
    "AW": {en: "Aruba", flagEmoji:"🇦🇼"}, 
    "AX": {en: "Åland Islands", flagEmoji:"🇦🇽"}, 
    "AZ": {en: "Azerbaijan", flagEmoji:"🇦🇿"}, 
    "BA": {en: "Bosnia and Herzegovina", flagEmoji:"🇧🇦"}, 
    "BB": {en: "Barbados", flagEmoji:"🇧🇧"}, 
    "BD": {en: "Bangladesh", flagEmoji:"🇧🇩"}, 
    "BE": {en: "Belgium", flagEmoji:"🇧🇪"}, 
    "BF": {en: "Burkina Faso", flagEmoji:"🇧🇫"}, 
    "BG": {en: "Bulgaria", flagEmoji:"🇧🇬"}, 
    "BH": {en: "Bahrain", flagEmoji:"🇧🇭"}, 
    "BI": {en: "Burundi", flagEmoji:"🇧🇮"}, 
    "BJ": {en: "Benin", flagEmoji:"🇧🇯"}, 
    "BL": {en: "Saint Barthélemy", flagEmoji:"🇧🇱"}, 
    "BM": {en: "Bermuda", flagEmoji:"🇧🇲"}, 
    "BN": {en: "Brunei Darussalam", flagEmoji:"🇧🇳"}, 
    "BO": {en: "Bolivia", flagEmoji:"🇧🇴"}, 
    "BQ": {en: "Bonaire, Sint Eustatius, and Saba", flagEmoji:"🇧🇶"}, 
    "BR": {en: "Brazil", flagEmoji:"🇧🇷"}, 
    "BS": {en: "Bahamas", flagEmoji:"🇧🇸"}, 
    "BT": {en: "Bhutan", flagEmoji:"🇧🇹"}, 
    "BV": {en: "Bouvet Island", flagEmoji:"🇧🇻"}, 
    "BW": {en: "Botswana", flagEmoji:"🇧🇼"}, 
    "BY": {en: "Belarus", flagEmoji:"🇧🇾"}, 
    "BZ": {en: "Belize", flagEmoji:"🇧🇿"}, 
    "CA": {en: "Canada", flagEmoji:"🇨🇦"}, 
    "CC": {en: "Cocos (Keeling) Islands", flagEmoji:"🇨🇨"}, 
    "CD": {en: "Congo", flagEmoji:"🇨🇩"}, 
    "CF": {en: "Central African Republic", flagEmoji:"🇨🇫"}, 
    "CG": {en: "Congo", flagEmoji:"🇨🇬"}, 
    "CH": {en: "Switzerland", flagEmoji:"🇨🇭"}, 
    "CI": {en: "Côte d'Ivoire", flagEmoji:"🇨🇮"}, 
    "CK": {en: "Cook Islands", flagEmoji:"🇨🇰"}, 
    "CL": {en: "Chile", flagEmoji:"🇨🇱"}, 
    "CM": {en: "Cameroon", flagEmoji:"🇨🇲"}, 
    "CN": {en: "China", flagEmoji:"🇨🇳"}, 
    "CO": {en: "Colombia", flagEmoji:"🇨🇴"}, 
    "CR": {en: "Costa Rica", flagEmoji:"🇨🇷"}, 
    "CU": {en: "Cuba", flagEmoji:"🇨🇺"}, 
    "CV": {en: "Cabo Verde", flagEmoji:"🇨🇻"}, 
    "CW": {en: "Curaçao", flagEmoji:"🇨🇼"}, 
    "CX": {en: "Christmas Island", flagEmoji:"🇨🇽"}, 
    "CY": {en: "Cyprus", flagEmoji:"🇨🇾"}, 
    "CZ": {en: "Czech Republic", flagEmoji:"🇨🇿"}, 
    "DE": {en: "Germany", flagEmoji:"🇩🇪"}, 
    "DJ": {en: "Djibouti", flagEmoji:"🇩🇯"}, 
    "DK": {en: "Denmark", flagEmoji:"🇩🇰"}, 
    "DM": {en: "Dominica", flagEmoji:"🇩🇲"}, 
    "DO": {en: "Dominican Republic", flagEmoji:"🇩🇴"}, 
    "DZ": {en: "Algeria", flagEmoji:"🇩🇿"}, 
    "EC": {en: "Ecuador", flagEmoji:"🇪🇨"}, 
    "EE": {en: "Estonia", flagEmoji:"🇪🇪"}, 
    "EG": {en: "Egypt", flagEmoji:"🇪🇬"}, 
    "EH": {en: "Western Sahara", flagEmoji:"🇪🇭"}, 
    "ER": {en: "Eritrea", flagEmoji:"🇪🇷"}, 
    "ES": {en: "Spain", flagEmoji:"🇪🇸"}, 
    "ET": {en: "Ethiopia", flagEmoji:"🇪🇹"}, 
    "FI": {en: "Finland", flagEmoji:"🇫🇮"}, 
    "FJ": {en: "Fiji", flagEmoji:"🇫🇯"}, 
    "FK": {en: "Falkland Islands", flagEmoji:"🇫🇰"}, 
    "FM": {en: "Micronesia", flagEmoji:"🇫🇲"}, 
    "FO": {en: "Faroe Islands", flagEmoji:"🇫🇴"}, 
    "FR": {en: "France", flagEmoji:"🇫🇷"}, 
    "GA": {en: "Gabon", flagEmoji:"🇬🇦"}, 
    "GB": {en: "United Kingdom", flagEmoji:"🇬🇧"}, 
    "GD": {en: "Grenada", flagEmoji:"🇬🇩"}, 
    "GE": {en: "Georgia", flagEmoji:"🇬🇪"}, 
    "GF": {en: "French Guiana", flagEmoji:"🇬🇫"}, 
    "GG": {en: "Guernsey", flagEmoji:"🇬🇬"}, 
    "GH": {en: "Ghana", flagEmoji:"🇬🇭"}, 
    "GI": {en: "Gibraltar", flagEmoji:"🇬🇮"}, 
    "GL": {en: "Greenland", flagEmoji:"🇬🇱"}, 
    "GM": {en: "Gambia", flagEmoji:"🇬🇲"}, 
    "GN": {en: "Guinea", flagEmoji:"🇬🇳"}, 
    "GP": {en: "Guadeloupe", flagEmoji:"🇬🇵"}, 
    "GQ": {en: "Equatorial Guinea", flagEmoji:"🇬🇶"}, 
    "GR": {en: "Greece", flagEmoji:"🇬🇷"}, 
    "GS": {en: "South Georgia and the South Sandwich Islands", flagEmoji:"🇬🇸"}, 
    "GT": {en: "Guatemala", flagEmoji:"🇬🇹"}, 
    "GU": {en: "Guam", flagEmoji:"🇬🇺"}, 
    "GW": {en: "Guinea-Bissau", flagEmoji:"🇬🇼"}, 
    "GY": {en: "Guyana", flagEmoji:"🇬🇾"}, 
    "HK": {en: "Hong Kong", flagEmoji:"🇭🇰"}, 
    "HM": {en: "Heard Island and McDonald Islands", flagEmoji:"🇭🇲"}, 
    "HN": {en: "Honduras", flagEmoji:"🇭🇳"}, 
    "HR": {en: "Croatia", flagEmoji:"🇭🇷"}, 
    "HT": {en: "Haiti", flagEmoji:"🇭🇹"}, 
    "HU": {en: "Hungary", flagEmoji:"🇭🇺"}, 
    "ID": {en: "Indonesia", flagEmoji:"🇮🇩"}, 
    "IE": {en: "Ireland", flagEmoji:"🇮🇪"}, 
    "IL": {en: "Israel", flagEmoji:"🇮🇱"}, 
    "IM": {en: "Isle of Man", flagEmoji:"🇮🇲"}, 
    "IN": {en: "India", flagEmoji:"🇮🇳"}, 
    "IO": {en: "British Indian Ocean Territory", flagEmoji:"🇮🇴"}, 
    "IQ": {en: "Iraq", flagEmoji:"🇮🇶"}, 
    "IR": {en: "Iran", flagEmoji:"🇮🇷"}, 
    "IS": {en: "Iceland", flagEmoji:"🇮🇸"}, 
    "IT": {en: "Italy", flagEmoji:"🇮🇹"}, 
    "JE": {en: "Jersey", flagEmoji:"🇯🇪"}, 
    "JM": {en: "Jamaica", flagEmoji:"🇯🇲"}, 
    "JO": {en: "Jordan", flagEmoji:"🇯🇴"}, 
    "JP": {en: "Japan", flagEmoji:"🇯🇵"}, 
    "KE": {en: "Kenya", flagEmoji:"🇰🇪"}, 
    "KG": {en: "Kyrgyzstan", flagEmoji:"🇰🇬"}, 
    "KH": {en: "Cambodia", flagEmoji:"🇰🇭"}, 
    "KI": {en: "Kiribati", flagEmoji:"🇰🇮"}, 
    "KM": {en: "Comoros", flagEmoji:"🇰🇲"}, 
    "KN": {en: "Saint Kitts and Nevis", flagEmoji:"🇰🇳"}, 
    "KP": {en: "North Korea", flagEmoji:"🇰🇵"}, 
    "KR": {en: "South Korea", flagEmoji:"🇰🇷"}, 
    "KW": {en: "Kuwait", flagEmoji:"🇰🇼"}, 
    "KY": {en: "Cayman Islands", flagEmoji:"🇰🇾"}, 
    "KZ": {en: "Kazakhstan", flagEmoji:"🇰🇿"}, 
    "LA": {en: "Lao People's Democratic Republic", flagEmoji:"🇱🇦"}, 
    "LB": {en: "Lebanon", flagEmoji:"🇱🇧"}, 
    "LC": {en: "Saint Lucia", flagEmoji:"🇱🇨"}, 
    "LI": {en: "Liechtenstein", flagEmoji:"🇱🇮"}, 
    "LK": {en: "Sri Lanka", flagEmoji:"🇱🇰"}, 
    "LR": {en: "Liberia", flagEmoji:"🇱🇷"}, 
    "LS": {en: "Lesotho", flagEmoji:"🇱🇸"}, 
    "LT": {en: "Lithuania", flagEmoji:"🇱🇹"}, 
    "LU": {en: "Luxembourg", flagEmoji:"🇱🇺"}, 
    "LV": {en: "Latvia", flagEmoji:"🇱🇻"}, 
    "LY": {en: "Libya", flagEmoji:"🇱🇾"}, 
    "MA": {en: "Morocco", flagEmoji:"🇲🇦"}, 
    "MC": {en: "Monaco", flagEmoji:"🇲🇨"}, 
    "MD": {en: "Moldova", flagEmoji:"🇲🇩"}, 
    "ME": {en: "Montenegro", flagEmoji:"🇲🇪"}, 
    "MF": {en: "Saint Martin (French Part)", flagEmoji:"🇲🇫"}, 
    "MG": {en: "Madagascar", flagEmoji:"🇲🇬"}, 
    "MH": {en: "Marshall Islands", flagEmoji:"🇲🇭"}, 
    "MK": {en: "North Macedonia", flagEmoji:"🇲🇰"}, 
    "ML": {en: "Mali", flagEmoji:"🇲🇱"}, 
    "MM": {en: "Myanmar", flagEmoji:"🇲🇲"}, 
    "MN": {en: "Mongolia", flagEmoji:"🇲🇳"}, 
    "MO": {en: "Macao", flagEmoji:"🇲🇴"}, 
    "MP": {en: "Northern Mariana Islands", flagEmoji:"🇲🇵"}, 
    "MQ": {en: "Martinique", flagEmoji:"🇲🇶"}, 
    "MR": {en: "Mauritania", flagEmoji:"🇲🇷"}, 
    "MS": {en: "Montserrat", flagEmoji:"🇲🇸"}, 
    "MT": {en: "Malta", flagEmoji:"🇲🇹"}, 
    "MU": {en: "Mauritius", flagEmoji:"🇲🇺"}, 
    "MV": {en: "Maldives", flagEmoji:"🇲🇻"}, 
    "MW": {en: "Malawi", flagEmoji:"🇲🇼"}, 
    "MX": {en: "Mexico", flagEmoji:"🇲🇽"}, 
    "MY": {en: "Malaysia", flagEmoji:"🇲🇾"}, 
    "MZ": {en: "Mozambique", flagEmoji:"🇲🇿"}, 
    "NA": {en: "Namibia", flagEmoji:"🇳🇦"}, 
    "NC": {en: "New Caledonia", flagEmoji:"🇳🇨"}, 
    "NE": {en: "Niger", flagEmoji:"🇳🇪"}, 
    "NF": {en: "Norfolk Island", flagEmoji:"🇳🇫"}, 
    "NG": {en: "Nigeria", flagEmoji:"🇳🇬"}, 
    "NI": {en: "Nicaragua", flagEmoji:"🇳🇮"}, 
    "NL": {en: "Netherlands", flagEmoji:"🇳🇱"}, 
    "NO": {en: "Norway", flagEmoji:"🇳🇴"}, 
    "NP": {en: "Nepal", flagEmoji:"🇳🇵"}, 
    "NR": {en: "Nauru", flagEmoji:"🇳🇷"}, 
    "NU": {en: "Niue", flagEmoji:"🇳🇺"}, 
    "NZ": {en: "New Zealand", flagEmoji:"🇳🇿"}, 
    "OM": {en: "Oman", flagEmoji:"🇴🇲"}, 
    "PA": {en: "Panama", flagEmoji:"🇵🇦"}, 
    "PE": {en: "Peru", flagEmoji:"🇵🇪"}, 
    "PF": {en: "French Polynesia", flagEmoji:"🇵🇫"}, 
    "PG": {en: "Papua New Guinea", flagEmoji:"🇵🇬"}, 
    "PH": {en: "Philippines", flagEmoji:"🇵🇭"}, 
    "PK": {en: "Pakistan", flagEmoji:"🇵🇰"}, 
    "PL": {en: "Poland", flagEmoji:"🇵🇱"}, 
    "PM": {en: "Saint Pierre and Miquelon", flagEmoji:"🇵🇲"}, 
    "PN": {en: "Pitcairn", flagEmoji:"🇵🇳"}, 
    "PR": {en: "Puerto Rico", flagEmoji:"🇵🇷"}, 
    "PS": {en: "Palestine", flagEmoji:"🇵🇸"}, 
    "PT": {en: "Portugal", flagEmoji:"🇵🇹"}, 
    "PW": {en: "Palau", flagEmoji:"🇵🇼"}, 
    "PY": {en: "Paraguay", flagEmoji:"🇵🇾"}, 
    "QA": {en: "Qatar", flagEmoji:"🇶🇦"}, 
    "RE": {en: "Réunion", flagEmoji:"🇷🇪"}, 
    "RO": {en: "Romania", flagEmoji:"🇷🇴"}, 
    "RS": {en: "Serbia", flagEmoji:"🇷🇸"}, 
    "RU": {en: "Russian", flagEmoji:"🇷🇺"}, 
    "RW": {en: "Rwanda", flagEmoji:"🇷🇼"}, 
    "SA": {en: "Saudi Arabia", flagEmoji:"🇸🇦"}, 
    "SB": {en: "Solomon Islands", flagEmoji:"🇸🇧"}, 
    "SC": {en: "Seychelles", flagEmoji:"🇸🇨"}, 
    "SD": {en: "Sudan", flagEmoji:"🇸🇩"}, 
    "SE": {en: "Sweden", flagEmoji:"🇸🇪"}, 
    "SG": {en: "Singapore", flagEmoji:"🇸🇬"}, 
    "SH": {en: "Saint Helena, Ascension Island, Tristan da Cunha", flagEmoji:"🇸🇭"}, 
    "SI": {en: "Slovenia", flagEmoji:"🇸🇮"}, 
    "SJ": {en: "Svalbard and Jan Mayen", flagEmoji:"🇸🇯"}, 
    "SK": {en: "Slovakia", flagEmoji:"🇸🇰"}, 
    "SL": {en: "Sierra Leone", flagEmoji:"🇸🇱"}, 
    "SM": {en: "San Marino", flagEmoji:"🇸🇲"}, 
    "SN": {en: "Senegal", flagEmoji:"🇸🇳"}, 
    "SO": {en: "Somalia", flagEmoji:"🇸🇴"}, 
    "SR": {en: "Suriname", flagEmoji:"🇸🇷"}, 
    "SS": {en: "South Sudan", flagEmoji:"🇸🇸"}, 
    "ST": {en: "Sao Tome and Principe", flagEmoji:"🇸🇹"}, 
    "SV": {en: "El Salvador", flagEmoji:"🇸🇻"}, 
    "SX": {en: "Sint Maarten (Dutch Part)", flagEmoji:"🇸🇽"}, 
    "SY": {en: "Syrian Arab Republic", flagEmoji:"🇸🇾"}, 
    "SZ": {en: "Eswatini", flagEmoji:"🇸🇿"}, 
    "TC": {en: "Turks and Caicos Islands", flagEmoji:"🇹🇨"}, 
    "TD": {en: "Chad", flagEmoji:"🇹🇩"}, 
    "TF": {en: "French Southern Territories", flagEmoji:"🇹🇫"}, 
    "TG": {en: "Togo", flagEmoji:"🇹🇬"}, 
    "TH": {en: "Thailand", flagEmoji:"🇹🇭"}, 
    "TJ": {en: "Tajikistan", flagEmoji:"🇹🇯"}, 
    "TK": {en: "Tokelau", flagEmoji:"🇹🇰"}, 
    "TL": {en: "Timor-Leste", flagEmoji:"🇹🇱"}, 
    "TM": {en: "Turkmenistan", flagEmoji:"🇹🇲"}, 
    "TN": {en: "Tunisia", flagEmoji:"🇹🇳"}, 
    "TO": {en: "Tonga", flagEmoji:"🇹🇴"}, 
    "TR": {en: "Türkiye", flagEmoji:"🇹🇷"}, 
    "TT": {en: "Trinidad and Tobago", flagEmoji:"🇹🇹"}, 
    "TV": {en: "Tuvalu", flagEmoji:"🇹🇻"}, 
    "TW": {en: "Taiwan", flagEmoji:"🇹🇼"}, 
    "TZ": {en: "Tanzania", flagEmoji:"🇹🇿"}, 
    "UA": {en: "Ukraine", flagEmoji:"🇺🇦"}, 
    "UG": {en: "Uganda", flagEmoji:"🇺🇬"}, 
    "UM": {en: "United States Minor Outlying Islands", flagEmoji:"🇺🇲"}, 
    "US": {en: "United States of America", flagEmoji:"🇺🇸"}, 
    "UY": {en: "Uruguay", flagEmoji:"🇺🇾"}, 
    "UZ": {en: "Uzbekistan", flagEmoji:"🇺🇿"}, 
    "VA": {en: "Vatican City", flagEmoji:"🇻🇦"}, 
    "VC": {en: "Saint Vincent and the Grenadines", flagEmoji:"🇻🇨"}, 
    "VE": {en: "Venezuela", flagEmoji:"🇻🇪"}, 
    "VG": {en: "Virgin Islands (British)", flagEmoji:"🇻🇬"}, 
    "VI": {en: "Virgin Islands (U.S.)", flagEmoji:"🇻🇮"}, 
    "VN": {en: "Vietnam", flagEmoji:"🇻🇳"}, 
    "VU": {en: "Vanuatu", flagEmoji:"🇻🇺"}, 
    "WF": {en: "Wallis and Futuna", flagEmoji:"🇼🇫"}, 
    "WS": {en: "Samoa", flagEmoji:"🇼🇸"}, 
    "YE": {en: "Yemen", flagEmoji:"🇾🇪"}, 
    "YT": {en: "Mayotte", flagEmoji:"🇾🇹"}, 
    "ZA": {en: "South Africa", flagEmoji:"🇿🇦"}, 
    "ZM": {en: "Zambia", flagEmoji:"🇿🇲"}, 
    "ZW": {en: "Zimbabwe", flagEmoji:"🇿🇼"}, 
};
