import { Box } from "../away/Box";

/** see: https://en.wikipedia.org/wiki/ISO_639-1 */
export class Iso6391LanguageCodeBox extends Box<Iso6391LanguageCode>{
    private __Iso6391LanguageCodeBox__:undefined;

    constructor(data:Iso6391LanguageCode,onValidationFail?:()=>void){
        if(!AllIso6391LanguageCodes.includes(data)){
            onValidationFail?.();
            throw new Error(`Bad data: Not an ISO 639-1 value: ${data}`);
        }
        super(data);
    }

    maybeGetEnglishName():string|undefined{
        return dataMap[this._data.toLowerCase()]?.englishName;
    }

    maybeGetNativeName():string|undefined{
        return dataMap[this._data.toLowerCase()]?.nativeName;
    }

    /** Will return the native name, English name if not available, and if that fails, the character code. */
    getClosestNameToNative():string{
        return this.maybeGetNativeName()||this.maybeGetEnglishName()||this._data;
    }
}

export type Iso6391LanguageCode = typeof AllIso6391LanguageCodes[number];
export const AllIso6391LanguageCodes = [
    "aa",
    "af",
    "ak",
    "ab",
    "sq",
    "am",
    "ar",
    "an",
    "hy",
    "as",
    "av",
    "ae",
    "ay",
    "az",
    "bm",
    "ba",
    "eu",
    "be",
    "bn",
    "bi",
    "bs",
    "br",
    "bg",
    "my",
    "ca",
    "ch",
    "ce",
    "ny",
    "zh",
    "cu",
    "cv",
    "kw",
    "co",
    "cr",
    "hr",
    "cs",
    "da",
    "dv",
    "nl",
    "dz",
    "en",
    "eo",
    "et",
    "ee",
    "fo",
    "fj",
    "fi",
    "fr",
    "fy",
    "ff",
    "gd",
    "gl",
    "lg",
    "ka",
    "de",
    "el",
    "kl",
    "gn",
    "gu",
    "ht",
    "ha",
    "he",
    "hz",
    "hi",
    "ho",
    "hu",
    "is",
    "io",
    "ig",
    "id",
    "ia",
    "ie",
    "iu",
    "ik",
    "ga",
    "it",
    "ja",
    "jv",
    "kn",
    "kr",
    "ks",
    "kk",
    "km",
    "ki",
    "rw",
    "ky",
    "kv",
    "kg",
    "ko",
    "kj",
    "ku",
    "lo",
    "la",
    "lv",
    "li",
    "ln",
    "lt",
    "lu",
    "lb",
    "mk",
    "mg",
    "ms",
    "ml",
    "mt",
    "gv",
    "mi",
    "mr",
    "mh",
    "mn",
    "na",
    "nv",
    "nd",
    "nr",
    "ng",
    "ne",
    "no",
    "nb",
    "nn",
    "ii",
    "oc",
    "oj",
    "or",
    "om",
    "os",
    "pi",
    "ps",
    "fa",
    "pl",
    "pt",
    "pa",
    "qu",
    "ro",
    "rm",
    "rn",
    "ru",
    "se",
    "sm",
    "sg",
    "sa",
    "sc",
    "sr",
    "sn",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "st",
    "es",
    "su",
    "sw",
    "ss",
    "sv",
    "tl",
    "ty",
    "tg",
    "ta",
    "tt",
    "te",
    "th",
    "bo",
    "ti",
    "to",
    "ts",
    "tn",
    "tr",
    "tk",
    "tw",
    "ug",
    "uk",
    "ur",
    "uz",
    "ve",
    "vi",
    "vo",
    "wa",
    "cy",
    "wo",
    "xh",
    "yi",
    "yo",
    "za",
    "zu"
] as const;


const dataMap: {
    [code in Iso6391LanguageCode]:{
        englishName:string,
        nativeName?:string,
    }
} = {
    "aa": {englishName: "Afar", nativeName: undefined},
    "ab": {englishName: "Abkhazian", nativeName: undefined},
    "ae": {englishName: "Avestan", nativeName: undefined},
    "af": {englishName: "Afrikaans", nativeName: "Afrikaans"},
    "ak": {englishName: "Akan", nativeName: undefined},
    "am": {englishName: "Amharic", nativeName: "አማርኛ"},
    "an": {englishName: "Aragonese", nativeName: undefined},
    "ar": {englishName: "Arabic", nativeName: "العربية"},
    "as": {englishName: "Assamese", nativeName: "অসমীয়া"},
    "av": {englishName: "Avaric", nativeName: undefined},
    "ay": {englishName: "Aymara", nativeName: undefined},
    "az": {englishName: "Azerbaijani", nativeName: "Azərbaycan"},
    "ba": {englishName: "Bashkir", nativeName: "Башҡорт"},
    "be": {englishName: "Belarusian", nativeName: "беларуская"},
    "bg": {englishName: "Bulgarian", nativeName: "български"},
    "bi": {englishName: "Bislama", nativeName: undefined},
    "bm": {englishName: "Bambara", nativeName: undefined},
    "bn": {englishName: "Bengali", nativeName: "বাংলা"},
    "bo": {englishName: "Tibetan", nativeName: "བོད་ཡིག"},
    "br": {englishName: "Breton", nativeName: "brezhoneg"},
    "bs": {englishName: "Bosnian", nativeName: "bosanski/босански"},
    "ca": {englishName: "Catalan, Valencian", nativeName: "català"},
    "ce": {englishName: "Chechen", nativeName: undefined},
    "ch": {englishName: "Chamorro", nativeName: undefined},
    "co": {englishName: "Corsican", nativeName: "Corsu"},
    "cr": {englishName: "Cree", nativeName: undefined},
    "cs": {englishName: "Czech", nativeName: "čeština"},
    "cu": {englishName: "Church Slavonic, Old Slavonic, Old Church Slavonic", nativeName: undefined},
    "cv": {englishName: "Chuvash", nativeName: undefined},
    "cy": {englishName: "Welsh", nativeName: "Cymraeg"},
    "da": {englishName: "Danish", nativeName: "dansk"},
    "de": {englishName: "German", nativeName: "Deutsch"},
    "dv": {englishName: "Divehi, Dhivehi, Maldivian", nativeName: "ދިވެހިބަސް"},
    "dz": {englishName: "Dzongkha", nativeName: undefined},
    "ee": {englishName: "Ewe", nativeName: undefined},
    "el": {englishName: "Greek, Modern (1453–)", nativeName: "Ελληνικά"},
    "en": {englishName: "English", nativeName: "English"},
    "eo": {englishName: "Esperanto", nativeName: undefined},
    "es": {englishName: "Spanish, Castilian", nativeName: "español"},
    "et": {englishName: "Estonian", nativeName: "eesti"},
    "eu": {englishName: "Basque", nativeName: "euskara"},
    "fa": {englishName: "Persian", nativeName: "فارسى"},
    "ff": {englishName: "Fulah", nativeName: undefined},
    "fi": {englishName: "Finnish", nativeName: "suomi"},
    "fj": {englishName: "Fijian", nativeName: "Filipino"},
    "fo": {englishName: "Faroese", nativeName: "føroyskt"},
    "fr": {englishName: "French", nativeName: "français"},
    "fy": {englishName: "Western Frisian", nativeName: "Frysk"},
    "ga": {englishName: "Irish", nativeName: "Gaeilge"},
    "gd": {englishName: "Gaelic, Scottish Gaelic", nativeName: "Gàidhlig"},
    "gl": {englishName: "Galician", nativeName: "galego"},
    "gn": {englishName: "Guarani", nativeName: undefined},
    "gu": {englishName: "Gujarati", nativeName: "ગુજરાતી"},
    "gv": {englishName: "Manx", nativeName: undefined},
    "ha": {englishName: "Hausa", nativeName: "Hausa"},
    "he": {englishName: "Hebrew", nativeName: "עברית"},
    "hi": {englishName: "Hindi", nativeName: "हिंदी"},
    "ho": {englishName: "Hiri Motu", nativeName: undefined},
    "hr": {englishName: "Croatian", nativeName: "hrvatski"},
    "ht": {englishName: "Haitian, Haitian Creole", nativeName: undefined},
    "hu": {englishName: "Hungarian", nativeName: "magyar"},
    "hy": {englishName: "Armenian", nativeName: "Հայերեն"},
    "hz": {englishName: "Herero", nativeName: undefined},
    "ia": {englishName: "Interlingua (International Auxiliary Language Association)", nativeName: undefined},
    "id": {englishName: "Indonesian", nativeName: "Bahasa Indonesia"},
    "ie": {englishName: "Interlingue, Occidental", nativeName: undefined},
    "ig": {englishName: "Igbo", nativeName: "Igbo"},
    "ii": {englishName: "Sichuan Yi, Nuosu", nativeName: "ꆈꌠꁱꂷ"},
    "ik": {englishName: "Inupiaq", nativeName: undefined},
    "io": {englishName: "Ido", nativeName: undefined},
    "is": {englishName: "Icelandic", nativeName: "íslenska"},
    "it": {englishName: "Italian", nativeName: "italiano"},
    "iu": {englishName: "Inuktitut", nativeName: "Inuktitut /ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)"},
    "ja": {englishName: "Japanese", nativeName: "日本語"},
    "jv": {englishName: "Javanese", nativeName: undefined},
    "ka": {englishName: "Georgian", nativeName: "ქართული"},
    "kg": {englishName: "Kongo", nativeName: undefined},
    "ki": {englishName: "Kikuyu, Gikuyu", nativeName: undefined},
    "kj": {englishName: "Kuanyama, Kwanyama", nativeName: undefined},
    "kk": {englishName: "Kazakh", nativeName: "Қазақша"},
    "kl": {englishName: "Kalaallisut, Greenlandic", nativeName: "kalaallisut"},
    "km": {englishName: "Central Khmer", nativeName: "ខ្មែរ"},
    "kn": {englishName: "Kannada", nativeName: "ಕನ್ನಡ"},
    "ko": {englishName: "Korean", nativeName: "한국어"},
    "kr": {englishName: "Kanuri", nativeName: undefined},
    "ks": {englishName: "Kashmiri", nativeName: undefined},
    "ku": {englishName: "Kurdish", nativeName: undefined},
    "kv": {englishName: "Komi", nativeName: undefined},
    "kw": {englishName: "Cornish", nativeName: undefined},
    "ky": {englishName: "Kirghiz, Kyrgyz", nativeName: "Кыргыз"},
    "la": {englishName: "Latin", nativeName: undefined},
    "lb": {englishName: "Luxembourgish, Letzeburgesch", nativeName: "Lëtzebuergesch"},
    "lg": {englishName: "Ganda", nativeName: undefined},
    "li": {englishName: "Limburgan, Limburger, Limburgish", nativeName: undefined},
    "ln": {englishName: "Lingala", nativeName: undefined},
    "lo": {englishName: "Lao", nativeName: "ລາວ"},
    "lt": {englishName: "Lithuanian", nativeName: "lietuvių"},
    "lu": {englishName: "Luba-Katanga", nativeName: undefined},
    "lv": {englishName: "Latvian", nativeName: "latviešu"},
    "mg": {englishName: "Malagasy", nativeName: undefined},
    "mh": {englishName: "Marshallese", nativeName: undefined},
    "mi": {englishName: "Maori", nativeName: "Reo Māori"},
    "mk": {englishName: "Macedonian", nativeName: "македонски јазик"},
    "ml": {englishName: "Malayalam", nativeName: "മലയാളം"},
    "mn": {englishName: "Mongolian", nativeName: "Монгол хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ"},
    "mr": {englishName: "Marathi", nativeName: "मराठी"},
    "ms": {englishName: "Malay", nativeName: "Bahasa Malaysia"},
    "mt": {englishName: "Maltese", nativeName: "Malti"},
    "my": {englishName: "Burmese", nativeName: "Myanmar"},
    "na": {englishName: "Nauru", nativeName: undefined},
    "nb": {englishName: "Norwegian Bokmål", nativeName: "norsk (bokmål)"},
    "nd": {englishName: "North Ndebele", nativeName: undefined},
    "ne": {englishName: "Nepali", nativeName: "नेपाली (नेपाल)"},
    "ng": {englishName: "Ndonga", nativeName: undefined},
    "nl": {englishName: "Dutch, Flemish", nativeName: "Nederlands"},
    "nn": {englishName: "Norwegian Nynorsk", nativeName: "norsk (nynorsk)"},
    "no": {englishName: "Norwegian", nativeName: "norsk"},
    "nr": {englishName: "South Ndebele", nativeName: undefined},
    "nv": {englishName: "Navajo, Navaho", nativeName: undefined},
    "ny": {englishName: "Chichewa, Chewa, Nyanja", nativeName: undefined},
    "oc": {englishName: "Occitan", nativeName: "Occitan"},
    "oj": {englishName: "Ojibwa", nativeName: undefined},
    "om": {englishName: "Oromo", nativeName: undefined},
    "or": {englishName: "Oriya", nativeName: "ଓଡ଼ିଆ"},
    "os": {englishName: "Ossetian, Ossetic", nativeName: undefined},
    "pa": {englishName: "Punjabi, Panjabi", nativeName: "ਪੰਜਾਬੀ"},
    "pi": {englishName: "Pali", nativeName: undefined},
    "pl": {englishName: "Polish", nativeName: "polski"},
    "ps": {englishName: "Pashto, Pushto", nativeName: "پښتو"},
    "pt": {englishName: "Portuguese", nativeName: "Português"},
    "qu": {englishName: "Quechua", nativeName: "runasimi"},
    "rm": {englishName: "Romansh", nativeName: "Rumantsch"},
    "rn": {englishName: "Rundi", nativeName: undefined},
    "ro": {englishName: "Romanian, Moldavian, Moldovan", nativeName: "română"},
    "ru": {englishName: "Russian", nativeName: "русский"},
    "rw": {englishName: "Kinyarwanda", nativeName: "Kinyarwanda"},
    "sa": {englishName: "Sanskrit", nativeName: "संस्कृत"},
    "sc": {englishName: "Sardinian", nativeName: undefined},
    "sd": {englishName: "Sindhi", nativeName: undefined},
    "se": {englishName: "Northern Sami", nativeName: "davvisámegiella"},
    "sg": {englishName: "Sango", nativeName: undefined},
    "si": {englishName: "Sinhala, Sinhalese", nativeName: "සිංහල"},
    "sk": {englishName: "Slovak", nativeName: "slovenčina"},
    "sl": {englishName: "Slovenian", nativeName: "slovenski"},
    "sm": {englishName: "Samoan", nativeName: undefined},
    "sn": {englishName: "Shona", nativeName: undefined},
    "so": {englishName: "Somali", nativeName: undefined},
    "sq": {englishName: "Albanian", nativeName: "shqip"},
    "sr": {englishName: "Serbian", nativeName: "srpski/српски"},
    "ss": {englishName: "Swati", nativeName: undefined},
    "st": {englishName: "Southern Sotho", nativeName: "Sesotho sa Leboa"},
    "su": {englishName: "Sundanese", nativeName: undefined},
    "sv": {englishName: "Swedish", nativeName: "svenska"},
    "sw": {englishName: "Swahili", nativeName: "Kiswahili"},
    "ta": {englishName: "Tamil", nativeName: "தமிழ்"},
    "te": {englishName: "Telugu", nativeName: "తెలుగు"},
    "tg": {englishName: "Tajik", nativeName: "Тоҷикӣ"},
    "th": {englishName: "Thai", nativeName: "ไทย"},
    "ti": {englishName: "Tigrinya", nativeName: undefined},
    "tk": {englishName: "Turkmen", nativeName: "türkmençe"},
    "tl": {englishName: "Tagalog", nativeName: undefined},
    "tn": {englishName: "Tswana", nativeName: "Setswana"},
    "to": {englishName: "Tonga (Tonga Islands)", nativeName: undefined},
    "tr": {englishName: "Turkish", nativeName: "Türkçe"},
    "ts": {englishName: "Tsonga", nativeName: undefined},
    "tt": {englishName: "Tatar", nativeName: "Татарча"},
    "tw": {englishName: "Twi", nativeName: undefined},
    "ty": {englishName: "Tahitian", nativeName: undefined},
    "ug": {englishName: "Uighur, Uyghur", nativeName: "ئۇيغۇرچە"},
    "uk": {englishName: "Ukrainian", nativeName: "українська"},
    "ur": {englishName: "Urdu", nativeName: "اُردو"},
    "uz": {englishName: "Uzbek", nativeName: "Uzbek/Ўзбек"},
    "ve": {englishName: "Venda", nativeName: undefined},
    "vi": {englishName: "Vietnamese", nativeName: "Tiếng Việt"},
    "vo": {englishName: "Volapük", nativeName: "Wolof"},
    "wa": {englishName: "Walloon", nativeName: undefined},
    "wo": {englishName: "Wolof", nativeName: undefined},
    "xh": {englishName: "Xhosa", nativeName: "isiXhosa"},
    "yi": {englishName: "Yiddish", nativeName: undefined},
    "yo": {englishName: "Yoruba", nativeName: "Yoruba"},
    "za": {englishName: "Zhuang, Chuang", nativeName: undefined},
    "zh": {englishName: "Chinese", nativeName: "中文"},
    "zu": {englishName: "Zulu", nativeName: "isiZulu"},    
};