"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssignedIso31661A2CountryCodes = exports.MaybeGetIso31661A2CountryCodeEnglishName = exports.ExpectAssignedIso31661A2CountryCode = exports.ExpectIso31661A2CountryCode = void 0;
const Expect_1 = require("../away/Expect");
const Strings_1 = require("../strings/Strings");
const EscapeCode = "00";
/** see: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 */
function ExpectIso31661A2CountryCode(data, onBadData) {
    (0, Expect_1.Expect)(data.length === 2, `Not an ISO3166-1 alpha-2 value. Expected length: 2.`, onBadData);
    (0, Expect_1.Expect)((0, Strings_1.IsAlphabetic)(data) || EscapeCode, `Not an ISO3166-1 alpha-2 value. Expected alphabetic values or 00.`, onBadData);
}
exports.ExpectIso31661A2CountryCode = ExpectIso31661A2CountryCode;
function ExpectAssignedIso31661A2CountryCode(data, onBadData) {
    ExpectIso31661A2CountryCode(data, onBadData);
    (0, Expect_1.Expect)(exports.AssignedIso31661A2CountryCodes.includes(data), `Not a valid assigned Iso3166A2 country code.`);
}
exports.ExpectAssignedIso31661A2CountryCode = ExpectAssignedIso31661A2CountryCode;
/** Returns the name (hopefully). Will throw if you don't provide a valid country code. Will not throw if you simply provide an unassigned countrycode. */
function MaybeGetIso31661A2CountryCodeEnglishName(countryCode) {
    ExpectIso31661A2CountryCode(countryCode);
    return dataMap[countryCode.toUpperCase()]?.englishName;
}
exports.MaybeGetIso31661A2CountryCodeEnglishName = MaybeGetIso31661A2CountryCodeEnglishName;
/** Officially assigned codes. */
exports.AssignedIso31661A2CountryCodes = [
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IS",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW",
];
const dataMap = {
    "AD": { englishName: "Andorra" },
    "AE": { englishName: "United Arab Emirates" },
    "AF": { englishName: "Afghanistan" },
    "AG": { englishName: "Antigua and Barbuda" },
    "AI": { englishName: "Anguilla" },
    "AL": { englishName: "Albania" },
    "AM": { englishName: "Armenia" },
    "AO": { englishName: "Angola" },
    "AQ": { englishName: "Antarctica" },
    "AR": { englishName: "Argentina" },
    "AS": { englishName: "American Samoa" },
    "AT": { englishName: "Austria" },
    "AU": { englishName: "Australia" },
    "AW": { englishName: "Aruba" },
    "AX": { englishName: "Åland Islands" },
    "AZ": { englishName: "Azerbaijan" },
    "BA": { englishName: "Bosnia and Herzegovina" },
    "BB": { englishName: "Barbados" },
    "BD": { englishName: "Bangladesh" },
    "BE": { englishName: "Belgium" },
    "BF": { englishName: "Burkina Faso" },
    "BG": { englishName: "Bulgaria" },
    "BH": { englishName: "Bahrain" },
    "BI": { englishName: "Burundi" },
    "BJ": { englishName: "Benin" },
    "BL": { englishName: "Saint Barthélemy" },
    "BM": { englishName: "Bermuda" },
    "BN": { englishName: "Brunei Darussalam" },
    "BO": { englishName: "Bolivia (Plurinational State of)" },
    "BQ": { englishName: "Bonaire, Sint Eustatius, Saba" },
    "BR": { englishName: "Brazil" },
    "BS": { englishName: "Bahamas" },
    "BT": { englishName: "Bhutan" },
    "BV": { englishName: "Bouvet Island" },
    "BW": { englishName: "Botswana" },
    "BY": { englishName: "Belarus" },
    "BZ": { englishName: "Belize" },
    "CA": { englishName: "Canada" },
    "CC": { englishName: "Cocos (Keeling) Islands" },
    "CD": { englishName: "Congo (the Democratic Republic of the)" },
    "CF": { englishName: "Central African Republic" },
    "CG": { englishName: "Congo" },
    "CH": { englishName: "Switzerland" },
    "CI": { englishName: "Côte d'Ivoire" },
    "CK": { englishName: "Cook Islands" },
    "CL": { englishName: "Chile" },
    "CM": { englishName: "Cameroon" },
    "CN": { englishName: "China" },
    "CO": { englishName: "Colombia" },
    "CR": { englishName: "Costa Rica" },
    "CU": { englishName: "Cuba" },
    "CV": { englishName: "Cabo Verde" },
    "CW": { englishName: "Curaçao" },
    "CX": { englishName: "Christmas Island" },
    "CY": { englishName: "Cyprus" },
    "CZ": { englishName: "Czechia" },
    "DE": { englishName: "Germany" },
    "DJ": { englishName: "Djibouti" },
    "DK": { englishName: "Denmark" },
    "DM": { englishName: "Dominica" },
    "DO": { englishName: "Dominican Republic" },
    "DZ": { englishName: "Algeria" },
    "EC": { englishName: "Ecuador" },
    "EE": { englishName: "Estonia" },
    "EG": { englishName: "Egypt" },
    "EH": { englishName: "Western Sahara" },
    "ER": { englishName: "Eritrea" },
    "ES": { englishName: "Spain" },
    "ET": { englishName: "Ethiopia" },
    "FI": { englishName: "Finland" },
    "FJ": { englishName: "Fiji" },
    "FK": { englishName: "Falkland Islands (the) [Malvinas]" },
    "FM": { englishName: "Micronesia (Federated States of)" },
    "FO": { englishName: "Faroe Islands" },
    "FR": { englishName: "France" },
    "GA": { englishName: "Gabon" },
    "GB": { englishName: "United Kingdom" },
    "GD": { englishName: "Grenada" },
    "GE": { englishName: "Georgia" },
    "GF": { englishName: "French Guiana" },
    "GG": { englishName: "Guernsey" },
    "GH": { englishName: "Ghana" },
    "GI": { englishName: "Gibraltar" },
    "GL": { englishName: "Greenland" },
    "GM": { englishName: "Gambia" },
    "GN": { englishName: "Guinea" },
    "GP": { englishName: "Guadeloupe" },
    "GQ": { englishName: "Equatorial Guinea" },
    "GR": { englishName: "Greece" },
    "GS": { englishName: "South Georgia and the South Sandwich Islands" },
    "GT": { englishName: "Guatemala" },
    "GU": { englishName: "Guam" },
    "GW": { englishName: "Guinea-Bissau" },
    "GY": { englishName: "Guyana" },
    "HK": { englishName: "Hong Kong" },
    "HM": { englishName: "Heard Island and McDonald Islands" },
    "HN": { englishName: "Honduras" },
    "HR": { englishName: "Croatia" },
    "HT": { englishName: "Haiti" },
    "HU": { englishName: "Hungary" },
    "ID": { englishName: "Indonesia" },
    "IE": { englishName: "Ireland" },
    "IL": { englishName: "Israel" },
    "IM": { englishName: "Isle of Man" },
    "IN": { englishName: "India" },
    "IO": { englishName: "British Indian Ocean Territory" },
    "IQ": { englishName: "Iraq" },
    "IR": { englishName: "Iran" },
    "IS": { englishName: "Iceland" },
    "IT": { englishName: "Italy" },
    "JE": { englishName: "Jersey" },
    "JM": { englishName: "Jamaica" },
    "JO": { englishName: "Jordan" },
    "JP": { englishName: "Japan" },
    "KE": { englishName: "Kenya" },
    "KG": { englishName: "Kyrgyzstan" },
    "KH": { englishName: "Cambodia" },
    "KI": { englishName: "Kiribati" },
    "KM": { englishName: "Comoros" },
    "KN": { englishName: "Saint Kitts and Nevis" },
    "KP": { englishName: "Korea (the Democratic People's Republic of)" },
    "KR": { englishName: "Korea (the Republic of)" },
    "KW": { englishName: "Kuwait" },
    "KY": { englishName: "Cayman Islands" },
    "KZ": { englishName: "Kazakhstan" },
    "LA": { englishName: "Lao People's Democratic Republic" },
    "LB": { englishName: "Lebanon" },
    "LC": { englishName: "Saint Lucia" },
    "LI": { englishName: "Liechtenstein" },
    "LK": { englishName: "Sri Lanka" },
    "LR": { englishName: "Liberia" },
    "LS": { englishName: "Lesotho" },
    "LT": { englishName: "Lithuania" },
    "LU": { englishName: "Luxembourg" },
    "LV": { englishName: "Latvia" },
    "LY": { englishName: "Libya" },
    "MA": { englishName: "Morocco" },
    "MC": { englishName: "Monaco" },
    "MD": { englishName: "Moldova (the Republic of)" },
    "ME": { englishName: "Montenegro" },
    "MF": { englishName: "Saint Martin (French part)" },
    "MG": { englishName: "Madagascar" },
    "MH": { englishName: "Marshall Islands" },
    "MK": { englishName: "North Macedonia" },
    "ML": { englishName: "Mali" },
    "MM": { englishName: "Myanmar" },
    "MN": { englishName: "Mongolia" },
    "MO": { englishName: "Macao" },
    "MP": { englishName: "Northern Mariana Islands" },
    "MQ": { englishName: "Martinique" },
    "MR": { englishName: "Mauritania" },
    "MS": { englishName: "Montserrat" },
    "MT": { englishName: "Malta" },
    "MU": { englishName: "Mauritius" },
    "MV": { englishName: "Maldives" },
    "MW": { englishName: "Malawi" },
    "MX": { englishName: "Mexico" },
    "MY": { englishName: "Malaysia" },
    "MZ": { englishName: "Mozambique" },
    "NA": { englishName: "Namibia" },
    "NC": { englishName: "New Caledonia" },
    "NE": { englishName: "Niger" },
    "NF": { englishName: "Norfolk Island" },
    "NG": { englishName: "Nigeria" },
    "NI": { englishName: "Nicaragua" },
    "NL": { englishName: "Netherlands, Kingdom of the" },
    "NO": { englishName: "Norway" },
    "NP": { englishName: "Nepal" },
    "NR": { englishName: "Nauru" },
    "NU": { englishName: "Niue" },
    "NZ": { englishName: "New Zealand" },
    "OM": { englishName: "Oman" },
    "PA": { englishName: "Panama" },
    "PE": { englishName: "Peru" },
    "PF": { englishName: "French Polynesia" },
    "PG": { englishName: "Papua New Guinea" },
    "PH": { englishName: "Philippines" },
    "PK": { englishName: "Pakistan" },
    "PL": { englishName: "Poland" },
    "PM": { englishName: "Saint Pierre and Miquelon" },
    "PN": { englishName: "Pitcairn" },
    "PR": { englishName: "Puerto Rico" },
    "PS": { englishName: "Palestine, State of" },
    "PT": { englishName: "Portugal" },
    "PW": { englishName: "Palau" },
    "PY": { englishName: "Paraguay" },
    "QA": { englishName: "Qatar" },
    "RE": { englishName: "Réunion" },
    "RO": { englishName: "Romania" },
    "RS": { englishName: "Serbia" },
    "RU": { englishName: "Russian Federation" },
    "RW": { englishName: "Rwanda" },
    "SA": { englishName: "Saudi Arabia" },
    "SB": { englishName: "Solomon Islands" },
    "SC": { englishName: "Seychelles" },
    "SD": { englishName: "Sudan" },
    "SE": { englishName: "Sweden" },
    "SG": { englishName: "Singapore" },
    "SH": { englishName: "Saint Helena, Ascension Island, Tristan da Cunha" },
    "SI": { englishName: "Slovenia" },
    "SJ": { englishName: "Svalbard  Jan Mayen" },
    "SK": { englishName: "Slovakia" },
    "SL": { englishName: "Sierra Leone" },
    "SM": { englishName: "San Marino" },
    "SN": { englishName: "Senegal" },
    "SO": { englishName: "Somalia" },
    "SR": { englishName: "Suriname" },
    "SS": { englishName: "South Sudan" },
    "ST": { englishName: "Sao Tome and Principe" },
    "SV": { englishName: "El Salvador" },
    "SX": { englishName: "Sint Maarten (Dutch part)" },
    "SY": { englishName: "Syrian Arab Republic" },
    "SZ": { englishName: "Eswatini" },
    "TC": { englishName: "Turks and Caicos Islands" },
    "TD": { englishName: "Chad" },
    "TF": { englishName: "French Southern Territories" },
    "TG": { englishName: "Togo" },
    "TH": { englishName: "Thailand" },
    "TJ": { englishName: "Tajikistan" },
    "TK": { englishName: "Tokelau" },
    "TL": { englishName: "Timor-Leste" },
    "TM": { englishName: "Turkmenistan" },
    "TN": { englishName: "Tunisia" },
    "TO": { englishName: "Tonga" },
    "TR": { englishName: "Türkiye" },
    "TT": { englishName: "Trinidad and Tobago" },
    "TV": { englishName: "Tuvalu" },
    "TW": { englishName: "Taiwan" },
    "TZ": { englishName: "Tanzania, the United Republic of" },
    "UA": { englishName: "Ukraine" },
    "UG": { englishName: "Uganda" },
    "UM": { englishName: "United States Minor Outlying Islands" },
    "US": { englishName: "United States of America" },
    "UY": { englishName: "Uruguay" },
    "UZ": { englishName: "Uzbekistan" },
    "VA": { englishName: "Holy See" },
    "VC": { englishName: "Saint Vincent and the Grenadines" },
    "VE": { englishName: "Venezuela (Bolivarian Republic of)" },
    "VG": { englishName: "Virgin Islands (British)" },
    "VI": { englishName: "Virgin Islands (U.S.)" },
    "VN": { englishName: "Vietnam" },
    "VU": { englishName: "Vanuatu" },
    "WF": { englishName: "Wallis and Futuna" },
    "WS": { englishName: "Samoa" },
    "YE": { englishName: "Yemen" },
    "YT": { englishName: "Mayotte" },
    "ZA": { englishName: "South Africa" },
    "ZM": { englishName: "Zambia" },
    "ZW": { englishName: "Zimbabwe" },
};
