"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhitespaceCharacters = exports.JavascriptIdentifierCharacters = exports.AlphanumericCharacters = exports.NumericCharacters = exports.AlphebeticCharacters = exports.UppercaseAlphabetCharacters = exports.LowercaseAlphabetCharacters = void 0;
exports.LowercaseAlphabetCharacters = "abcdefghijklmnopqrstuvwxyz";
exports.UppercaseAlphabetCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
exports.AlphebeticCharacters = exports.LowercaseAlphabetCharacters + exports.UppercaseAlphabetCharacters;
exports.NumericCharacters = "0123456789";
exports.AlphanumericCharacters = exports.AlphebeticCharacters + exports.NumericCharacters;
exports.JavascriptIdentifierCharacters = exports.AlphebeticCharacters + exports.NumericCharacters + "$_";
exports.WhitespaceCharacters = " \n\r\t\f";
